-- begin DAVALEBA_MODEL
alter table DAVALEBA_MODEL add constraint FK_DAVALEBA_MODEL_ON_CAR foreign key (CAR_ID) references DAVALEBA_CAR(ID)^
create index IDX_DAVALEBA_MODEL_ON_CAR on DAVALEBA_MODEL (CAR_ID)^
-- end DAVALEBA_MODEL
-- begin DAVALEBA_CAR_MANUFACTURING
alter table DAVALEBA_CAR_MANUFACTURING add constraint FK_DAVALEBA_CAR_MANUFACTURING_ON_MODEL foreign key (MODEL_ID) references DAVALEBA_MODEL(ID)^
alter table DAVALEBA_CAR_MANUFACTURING add constraint FK_DAVALEBA_CAR_MANUFACTURING_ON_CAR foreign key (CAR_ID) references DAVALEBA_CAR(ID)^
create unique index IDX_DAVALEBA_CAR_MANUFACTURING_UNIQ_MANUFACTURER_CODE on DAVALEBA_CAR_MANUFACTURING (MANUFACTURER_CODE) ^
create unique index IDX_DAVALEBA_CAR_MANUFACTURING_UNIQ_NAME on DAVALEBA_CAR_MANUFACTURING (NAME) ^
create index IDX_DAVALEBA_CAR_MANUFACTURING_ON_MODEL on DAVALEBA_CAR_MANUFACTURING (MODEL_ID)^
create index IDX_DAVALEBA_CAR_MANUFACTURING_ON_CAR on DAVALEBA_CAR_MANUFACTURING (CAR_ID)^
-- end DAVALEBA_CAR_MANUFACTURING
-- begin DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR
alter table DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR add constraint FK_DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR_ON_CAR foreign key (CAR_ID) references DAVALEBA_CAR(ID)^
alter table DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR add constraint FK_DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID)^
alter table DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR add constraint FK_DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR_ON_COUNTERPARTY foreign key (COUNTERPARTY_ID) references DAVALEBA_COUNTERPARTY(ID)^
create index IDX_DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR_ON_CAR on DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR (CAR_ID)^
create index IDX_DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR_ON_MANAGER on DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR (MANAGER_ID)^
create index IDX_DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR_ON_COUNTERPARTY on DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR (COUNTERPARTY_ID)^
-- end DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR
-- begin DAVALEBA_CAR
alter table DAVALEBA_CAR add constraint FK_DAVALEBA_CAR_ON_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR foreign key (APPLICATION_FOR_THE_PURCHASE_OF_A_CAR_ID) references DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR(ID)^
create index IDX_DAVALEBA_CAR_ON_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR on DAVALEBA_CAR (APPLICATION_FOR_THE_PURCHASE_OF_A_CAR_ID)^
-- end DAVALEBA_CAR
-- begin DAVALEBA_COLOUR
create unique index IDX_DAVALEBA_COLOUR_UNIQ_NAME on DAVALEBA_COLOUR (NAME) ^
-- end DAVALEBA_COLOUR
-- begin DAVALEBA_NATURAL_PERSON
alter table DAVALEBA_NATURAL_PERSON add constraint FK_DAVALEBA_NATURAL_PERSON_ON_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR foreign key (APPLICATION_FOR_THE_PURCHASE_OF_A_CAR_ID) references DAVALEBA_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR(ID)^
create index IDX_DAVALEBA_NATURAL_PERSON_ON_APPLICATION_FOR_THE_PURCHASE_OF_A_CAR on DAVALEBA_NATURAL_PERSON (APPLICATION_FOR_THE_PURCHASE_OF_A_CAR_ID)^
-- end DAVALEBA_NATURAL_PERSON
-- begin DAVALEBA_COUNTRY
alter table DAVALEBA_COUNTRY add constraint FK_DAVALEBA_COUNTRY_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table DAVALEBA_COUNTRY add constraint FK_DAVALEBA_COUNTRY_ON_CAR_MANUFACTURERS foreign key (CAR_MANUFACTURERS_ID) references DAVALEBA_CAR_MANUFACTURING(ID)^
create index IDX_DAVALEBA_COUNTRY_ON_USER on DAVALEBA_COUNTRY (USER_ID)^
create index IDX_DAVALEBA_COUNTRY_ON_CAR_MANUFACTURERS on DAVALEBA_COUNTRY (CAR_MANUFACTURERS_ID)^
-- end DAVALEBA_COUNTRY
-- begin DAVALEBA_ASSEMBLY
alter table DAVALEBA_ASSEMBLY add constraint FK_DAVALEBA_ASSEMBLY_ON_CAR foreign key (CAR_ID) references DAVALEBA_CAR(ID)^
create index IDX_DAVALEBA_ASSEMBLY_ON_CAR on DAVALEBA_ASSEMBLY (CAR_ID)^
-- end DAVALEBA_ASSEMBLY
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_COUNTRY foreign key (COUNTRY_ID) references DAVALEBA_COUNTRY(ID)^
create index IDX_SEC_USER_ON_COUNTRY on SEC_USER (COUNTRY_ID)^
alter table SEC_USER add constraint FK_SEC_USER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_USER_ON_USER on SEC_USER (USER_ID)^
-- end SEC_USER
