alter table DAVALEBA_CAR_MANUFACTURING alter column CAR_ID rename to CAR_ID__U06042 ^
alter table DAVALEBA_CAR_MANUFACTURING drop constraint FK_DAVALEBA_CAR_MANUFACTURING_ON_CAR ;
drop index IDX_DAVALEBA_CAR_MANUFACTURING_ON_CAR ;
