alter table DAVALEBA_CAR add constraint FK_DAVALEBA_CAR_ON_CAR_MANUFACTURERS foreign key (CAR_MANUFACTURERS_ID) references DAVALEBA_CAR_MANUFACTURING(ID);
create index IDX_DAVALEBA_CAR_ON_CAR_MANUFACTURERS on DAVALEBA_CAR (CAR_MANUFACTURERS_ID);
